//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReactCRUDAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Client
    {
        public int UniqueId { get; set; }
        public Nullable<int> ClientId { get; set; }
        public string Name { get; set; }
        public string Tactical_Contact { get; set; }
        public string Operative_Contact { get; set; }
        public string Strategic_Contact { get; set; }
        public string Address { get; set; }
        public string Country { get; set; }
    }
}
