//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReactCRUDAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkingDay
    {
        public int UniqueId { get; set; }
        public int Month { get; set; }
        public int WDays { get; set; }
        public string Country { get; set; }
    }
}
