//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReactCRUDAPI.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class YUXI_OSS_DEV_Entities : DbContext
    {
        public YUXI_OSS_DEV_Entities()
            : base("name=YUXI_OSS_DEV_Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Client> Clients { get; set; }
        public virtual DbSet<Employee> Employees { get; set; }
        public virtual DbSet<Holiday> Holidays { get; set; }
        public virtual DbSet<Position> Positions { get; set; }
        public virtual DbSet<Project1> Projects1 { get; set; }
        public virtual DbSet<Sow> Sows { get; set; }
        public virtual DbSet<WorkingDay> WorkingDays { get; set; }
    }
}
